default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: clwy1234
  host: 127.0.0.1
  port: 3306 # MySQL默认端口

development:
  <<: *default
  database: market_api_development

test:
  <<: *default
  database: market_api_test

production:
  <<: *default
  database: market_api_production
  username: root
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>